language: node_js
node_js:
- lts/*
script:
- npm run lint
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: jpe3vS4RC6BchU95LynB81QMwvuOHy1D38Aiu1zOl7l9jqSei20srzTOCo7T1wQDkb6Z49LjbGifpljQW3eRidlFxAUcZz4sOa3AOKUvFB6uLCEAw6+kV+3z+/o4fWCpIc+hmD9u9DCt+3roRAWk1uptcFmxQNrK1Dhzgd+ix6fmtyC+EfBFlo2b/u/cYJl6XeKLShVEynTjwCqBqJvwB8lunpC2r9YC1o+11PnZxVs3GEt63b23plPePFryCGkGrVQrmt4T59A92VYX30pnHtPITtdSDIVUFCEwoiUul3IgHBqRPCYgzcvEvHn/FUb3+AtJmZyhYdfBE6YwfxhsfYrxYT/U9rnADgC92cNtHpxM4HnD2E8LEdgHfqYIr2ZB4je1DGvhbagoCbOnnPkxpCdqByvXiuZ+S/55Y5POveC2FutSjbYo0zhdvOq6mLAzZz57g15pSjBCp0VVCi/fzFYu4+Hfz8ulEkTo9pOn/ZEBhCUzQRdMd2Edn68JNBaX148BgvtFcVPK8Ez7x0dNe/mgcguuUCI9FEoAo2GAdUbi4Ei7/r/2SekEhRheMBleGse8dwYUpZ/OILJ/1Fdr6ybx4LE2E7FAKZGj/iwNRxr6PWJ0/ZREfipUcz+MZ81YoGzGDc4aaLdZjVm8AfUW/oKE5pF3YGat53zjPE0+JAQ=
